# Generated by Django 4.2 on 2023-05-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='products',
        ),
    ]
