# Generated by Django 4.1.7 on 2023-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.SlugField(blank=True, max_length=1023, null=True),
        ),
    ]
