# Generated by Django 4.1.7 on 2023-04-25 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
