# Generated by Django 4.1.7 on 2023-04-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_feedback_rating_alter_feedback_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
