# Generated by Django 4.2 on 2023-05-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyhistory',
            old_name='sell',
            new_name='sale',
        ),
    ]
