# Generated by Django 4.1.7 on 2023-04-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount_valid_until_order_unique_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
