# Generated by Django 4.2 on 2023-04-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_number_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
