# Generated by Django 4.2 on 2023-04-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_amount_discount_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.discount'),
        ),
    ]
