# Generated by Django 4.2 on 2023-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
